apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: Project allowing apps from a specific Git repo
  sourceRepos:
    - https://github.com/liorshasha/*
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lior-app
  namespace: argocd
spec:
  project: my-project
  source:
    repoURL: https://github.com/Liorshasha/argo-repo.git
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
